device: cuda
use_wandb: false

mode:
  is_train: true
  train_single_image: true

train_setting:
  max_steps:  100000
  inference_steps: 100

train_dataset:
  root: 'ImageNet2012'
  split: 'train'
  device: cuda:0
  batch_size: 32
  shuffle: true

test_dataset:
  root: 'ImageNet2012'
  split: 'test'

single_image:
  path: 'data/test.jpg'

model:
  encoder_type: 'pure_embedding'
  decoder_type: 'decoder_embedding'

  pure_embedding:
    device: ${device}
    query_num: 77
    feature_dim: 1024
    training_params:
      lr: 0.03
      min_betas: 0.9
      max_betas: 0.99
      weight_decay: 0.01
      warmup_steps: 10000
      T_mult: 1
      eta_min: 0.0003

  pure_index:

  encoder_embedding:

  encoder_index:

  decoder_embedding:
    device: ${device}
    unet_pretrained_model_name_or_path: 'stabilityai/stable-diffusion-2-1-base'
    half_precision_weights: False
    do_classifier_free_guidance: False

  decode_index:

  decode_index_small: